server:
  port: 8091

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'
    # 访问频次限制
    limit-count: 10
    # 白名单，不做频次拦截【微信的openai】o24OmvnupICccnkgfdG13pG4xlc4
    white-list: o24OmvnupICccnkgfdG13pG4xlc4


# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
# 支付配置；如果你申请了支付渠道，则可以配置 enable = true，否则就配置 false 走流程测试
alipay:
  enabled: true
  app_id: 9021000150690829
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCSKgMjIbNUKQ/Y9OZ8Q5QB1761AlhwrqkDPRqmV/QBpXb3dYIenYlC8WVN8ip/PGBqPCIsKHcDp5ZSE9tqXdO5v2QhYAb/GwpwZcoXdVjk52a/STdYzbFulxLIffOuDXxukMCdeL50MYDulm/I4YtJEYOPM1OgG1U53nIzSUzlcyWlmX4NvyU6d0973xX3klpbMXGYNsoUspsMbEvJRulJ8rm77nXM6yWyFJvAoxbzqqQ0WAxlhcyFWpB02jkRpYApmrFVdFKgHv2CJv3o+z0cA5kEtfxzPY0CWASt1VHixqrY0TJzNe2BD4aMoQVExRd/DQALSDgnKsHyALk2IevPAgMBAAECggEBAIeM4r/v/wkr04CXDjFr0pUq6begZziJIkDYqCBgLPBh7URs+7E81BD7IcH5taOt8JRVFDPzivwerW+M7s1kGniGoGu7TIHFKBc4rwS2VSxj1YvMcMGwcL5o6Ih7FkPySdWX9KmVUrsbNcEOTrjzQmMPFPz20rUG5DD4tNwPPHsEsRMEmC+L0DePZls6TD6Vn8uF4rgD/SMH8vSoiae/lHFFwPqV4wsl6iD72UH4kLW7sN5ojyKcTLYhmJelLD1hjSIwlXYT9zQsPwLTMvyaul0wePNPx1MZuJ5QFMn/i4+LaSXFdbiTKMLNng7a1oJBHXeKiiViyPBBOhXRKeD64yECgYEA8NXzrs4VWLKii6EACsY+5XRUolPNc1J5bTImTgg4P5y3fuXgiShbPONTEye9XieCD+PzL1G2G1WxarZZg7gCb+sACKK4C8OG9SSsNnG4xYI9LeeOQA2O2k/zWvQdSpp+yDrHY+XTCZDIIYbE8zmwzP5tMdO6lQNX8xkTTubTiUcCgYEAm14Kqo+mbih0fqpJZnSm53khrPb3OscnwhSe8KL4OF5yxvyKW7xJ7vY9ZooUgabuQ+OD0M6VnF5P5kNpKdyOikkcNM4XRuc6N4b1gJPvvQp4G319e29suL7GEPQ9W8nQaWXhdSFcPx8H8veNP7Sqmnpj79AItB5Y2/nk4ghSTTkCgYAURS25bMcHLCHaNrbWMVFh5qSo9Py51Bs8QZhPwQla8UnQeHCpmqfzO/7mAdZCcnjT9Y+mT+5P5qqEHMzz9SzfVpwuHeP3uYFGaMvF2VR/6zJTBsZGRd3cKhaFdT5x5Qb+u1PE6LcWewUdLUauYhCrcE6ofvWZTSq930JsxajQSQKBgCU10Lgoz2NyrPPpNMslBRRLHpWeUHfzWsJQzgA0B974P+UIdtqhrdNdhjcYuvCSWl5IDznjQFHDBL/RRU6RVFIqUGcVNN32YysJV6MDy1crOrjaxULa3N8iUa2d0VQ6cX/MtsKmysETXYQDZgDr9DArP+QfnvYEjqOgpgC8nXmBAoGANy4rWFbi1GGw/1bruzQcDnu3px8dzOABlXlKk+OWyXTawJGR6+EBxEF2kAaXpu4pAlW9wjeHGhISAskvv17huExOaeKgyQhDq5u4oJFPYlXNVhVNE6RbmTTDnWU8cm4FIF0tx95AIT6JSuJdki9SWPeOfYIij7+owcKYS03lc+w=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtp4wqIfnrJo4wPpbW+Pch2PvaQhf4Pngc2eEru1ekKW6YGQZUlDR6TBWtckv3kcxU7Lm3+nR91sK1hHw9Gl0k60kzNqaF43bMe13ZybTuDWazS4v6CLt7OAKfBCFEBOLR/NT9wnhgyVgQ2oZo0Y2whbdS0Iy2wQdgPamj7DtWGtiR20C5S376/KX+JP5NYm3JyOy80i2pZcKr4HsC8xyjIPZJILvWC2/l7ZWO+OjenxhjtIR9bmDz0eYEPd+9/+AtQmpR987kf65+yU3E9ahgzg0IKihjQ4c2OAmDhsMbhK8rmvqRYUkh9oZsr8w9oIlsCQNzAmYbwMLjUa7khjHYQIDAQAB
  notify_url: http://xfg-studio.natapp1.cc/api/v1/alipay/pay_notify
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do


# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# ChatGLM SDK Config
chatglm:
  sdk:
    zhipu:
      config:
        # 状态；true = 开启、false 关闭
        enabled: true
        # 官网地址
        api-host: https://open.bigmodel.cn/
        # 官网申请 https://open.bigmodel.cn/usercenter/apikeys - 自己可申请
        api-secret-key: bb70cc6355ef46cdb890e7b5359cf9c2.qD9j4XV15Dwa1kD8

# 微信公众号配置信息
# originalid：原始ID
# appid：个人AppID
# token：开通接口服务自定义设置
wx:
  config:
    originalid: gh_485263098cc1
    appid: wx0cca3987b4bc4258
    token: goldn

## 数据库配置；SpringBoot 默认连接池为 HikariDataSource
spring:
  datasource:
    username: root
    password: Jzy200305085851
    url: jdbc:mysql://120.26.196.227:3306/openai?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    pool-name: Retail_HikariCP
    minimum-idle: 15 #最小空闲连接数量
    idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
    maximum-pool-size: 25 #连接池最大连接数，默认是10
    auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
    max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
    connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
    connection-test-query: SELECT 1
  type: com.zaxxer.hikari.HikariDataSource

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml